const CLIENTE_INTERESSADO = 0;
const PAGAMENTO_QUITADO = 1;
const CLIENTE_CONFIRMADO = 2;
const CLIENTE_PARCEIRO = 3;
const CLIENTE_CRIANÇA = 4;

module.exports = {
  CLIENTE_INTERESSADO,
  PAGAMENTO_QUITADO,
  CLIENTE_CONFIRMADO,
  CLIENTE_PARCEIRO,
  CLIENTE_CRIANÇA,
};
